### ISSUE TITLE
Support multiple architectures with multiple copies of the native code

### ISSUE THREAD

**Issue by dumbbell** [rabbitmq/lz4-erlang#5]
In order to support multiple architectures in a single package, I would like be able to ship multiple copies of the NIF shared library and the Erlang code should load the appropriate one.

We could search for the native library in two places:
1. In `priv/$arch/lz4_nif.so`
2. In `priv/lz4_nif.so`

What I have in mind is based on the usual architecture triples used by Autoconf (exposed by Erlang) or LLVM to give a few examples.

The one exposed by Erlang is the one set by the `configure` script when Erlang was compiled:
```
1> erlang:system_info(system_architecture).
"amd64-portbld-freebsd13.0"
```

Unfortunately, there is no consistency in that triple: it is very dependent on the toolchain and user configuration at the time Erlang was compiled. So several values could mean the same architecture.

For instance on FreeBSD:
* The official Erlang package exposes `amd64-portbld-freebsd13.0`
* Erlang built from source in my home directory exposes `x86_64-unknown-freebsd13.0`

I prefer what LLVM does: the triple is normalized. Here is the list exposed by Rust, which uses LLVM internally:
```
$ rustc --print target-list
aarch64-fuchsia
aarch64-linux-android
aarch64-pc-windows-msvc
aarch64-unknown-cloudabi
aarch64-unknown-freebsd
...
arm-linux-androideabi
arm-unknown-linux-gnueabi
arm-unknown-linux-gnueabihf
arm-unknown-linux-musleabi
arm-unknown-linux-musleabihf
armebv7r-none-eabi
armebv7r-none-eabihf
armv4t-unknown-linux-gnueabi
armv5te-unknown-linux-gnueabi
armv5te-unknown-linux-musleabi
armv6-unknown-freebsd
armv6-unknown-netbsd-eabihf
armv7-linux-androideabi
armv7-unknown-cloudabi-eabihf
...
armv7r-none-eabi
armv7r-none-eabihf
asmjs-unknown-emscripten
hexagon-unknown-linux-musl
i586-pc-windows-msvc
i586-unknown-linux-gnu
i586-unknown-linux-musl
i586-wrs-vxworks
i686-apple-darwin
i686-linux-android
i686-pc-windows-gnu
i686-pc-windows-msvc
i686-unknown-cloudabi
...
x86_64-unknown-openbsd
x86_64-unknown-redox
x86_64-unknown-uefi
x86_64-uwp-windows-gnu
x86_64-wrs-vxworks
```
So what do you think if:
* We modify the native code loading to look into both directories;
* We normalize the triple returned by Erlang to an LLVM one to format the directory name?

On my laptop, this would give:
1. `amd64-portbld-freebsd13.0` -> `x86_64-unknown-freebsd`
2. Try to load `priv/x86_64-unknown-freebsd/lz4_nif.so`
3. Try to load `priv/lz4_nif.so`

Taking care of building all the copies and shipping them is not in scope for this issue.

**Comment by essen** [comment]
No complaints, sounds sensible. I don't know what `unknown` is though.

**Comment by dumbbell** [comment]
It is the "vendor". For most Unix, this will be `unknown`. For Windows, it is `pc` for instance. As far as I understand, this is used when the CPU is not enough to qualify the platform. I.e. the vendor adds incompatible stuff to the machine which changes things like the memory layout.
