### ISSUE TITLE
failed to compile on ubuntu 18.04

### ISSUE THREAD

**Issue by gy8409** [rabbitmq/lz4-erlang#7]
OS: Ubuntu 18.04 LTS
Erl: Erlang/OTP 20 [erts-9.3.3.13]

my deps defined in rebar.config:
{deps, [
  {syn, {git, "https://github.com/ostinelli/syn", {tag, "1.3.0"}}},
  {lager, {git, "https://github.com/erlang-lager/lager", {branch, "master"}}},
  {lz4, {git, "https://github.com/rabbitmq/lz4-erlang", {branch, "master"}}},
  {looking_glass, {git, "https://github.com/rabbitmq/looking_glass.git", {branch, "master"}}},
  rabbit
]}.

compile log:

===> Cleaning out goldrush...
===> Cleaning out lager...
===> Cleaning out looking_glass...
===> Cleaning out lz4...
===> Cleaning out syn...
===> Verifying dependencies...
===> Compiling syn
===> Compiling goldrush
===> Compiling lager
===> Compiling rabbit
_checkouts/rabbit/src/rabbit.erl:202: Warning: function default_restart_type/1 is unused

_checkouts/rabbit/src/rabbit_mnesia.erl:382: Warning: function is_registered_process_alive/1 is unused
_checkouts/rabbit/src/rabbit_mnesia.erl:682: Warning: function schema_info/1 is unused
_checkouts/rabbit/src/rabbit_mnesia.erl:686: Warning: function info/2 is unused

===> Compiling lz4
 DEP    host_triple
mv: cannot stat '/home/gy/relay/_build/default/lib/lz4/deps/host_triple/ebin/host_triple.app': No such file or directory
make[1]: Entering directory '/home/gy/relay/_build/default/lib/lz4/.erlang.mk/rebar'
./bootstrap
No beam files found.
Recompile: src/rebar
Recompile: src/rebar_abnfc_compiler
Recompile: src/rebar_app_utils
Recompile: src/rebar_appups
Recompile: src/rebar_asn1_compiler
Recompile: src/rebar_base_compiler
Recompile: src/rebar_cleaner
Recompile: src/rebar_config
Recompile: src/rebar_core
Recompile: src/rebar_cover_utils
Recompile: src/rebar_ct
src/rebar_ct.erl:291: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
Recompile: src/rebar_deps
Recompile: src/rebar_dia_compiler
Recompile: src/rebar_dialyzer
Recompile: src/rebar_edoc
Recompile: src/rebar_erlc_compiler
Recompile: src/rebar_erlydtl_compiler
Recompile: src/rebar_escripter
Recompile: src/rebar_eunit
src/rebar_eunit.erl:282: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
Recompile: src/rebar_file_utils
Recompile: src/rebar_getopt
Recompile: src/rebar_lfe_compiler
Recompile: src/rebar_log
Recompile: src/rebar_metacmds
Recompile: src/rebar_mustache
Recompile: src/rebar_neotoma_compiler
Recompile: src/rebar_otp_app
Recompile: src/rebar_otp_appup
Recompile: src/rebar_port_compiler
Recompile: src/rebar_proto_compiler
Recompile: src/rebar_proto_gpb_compiler
Recompile: src/rebar_protobuffs_compiler
Recompile: src/rebar_qc
Recompile: src/rebar_rand_compat
Recompile: src/rebar_rel_utils
Recompile: src/rebar_reltool
Recompile: src/rebar_require_vsn
Recompile: src/rebar_shell
Recompile: src/rebar_subdirs
Recompile: src/rebar_templater
Recompile: src/rebar_upgrade
Recompile: src/rebar_utils
Recompile: src/rebar_xref
Recompile: src/rmemo
==> rebar (compile)
==> rebar (escriptize)
Congratulations! You now have a self-contained script called "rebar" in
your current working directory. Place this script anywhere in your path
and you can use rebar to build OTP-compliant apps.
make[1]: Leaving directory '/home/gy/relay/_build/default/lib/lz4/.erlang.mk/rebar'
/home/gy/relay/_build/default/lib/lz4
**Error: No Makefile to build dependency /home/gy/relay/_build/default/lib/lz4/deps/lz4_src.
erlang.mk:4183: recipe for target 'deps' failed**
make: *** [deps] Error 2
===> Hook for compile failed!

**Comment by gy8409** [comment]
After I edit lz4_nif.erl like below
> -include_lib("**../deps/**host_triple/include/code_loading.hrl").

 and run 

> sudo apt-get install -y liblz4-1

compile succeed.

**Comment by essen** [comment]
It compiled fine in your previous build log so I dont' think you need to edit anything. You also do not need to have lz4 installed as the source is fetched and built directly.

Anyway please don't open separate tickets for the same "doesn't build via Rebar issue" because that's probably what this is.
