### ISSUE TITLE
erlang.mk upgrade for Erlang 23 compatibility

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/lz4-erlang#8]
Looks like `-lerl_interface` is not available in OTP 23. We should bump erlang.mk which removes its use:

 * https://github.com/ninenines/erlang.mk/commit/2331c3443e2723209d6be0ceba71890c3e521505
 * https://github.com/ninenines/erlang.mk/commit/ada293a1cdf9fdf60998dbafe21f74d56a4d1be3

@dumbbell @essen do we have to keep erlang.mk in sync for standalone libraries such as this one (or Looking Glass, or Ra which depends on Looking Glass)?

**Comment by essen** [comment]
The top-level project's Erlang.mk is the one used to build. So updating Erlang.mk only really matters in projects you are running `make`.

I would say you don't need to aggressively update Erlang.mk in all dependencies. My own projects' Erlang.mk are not in sync for example. I only update them when there's a known issue or I need a feature. For OTP 23 I therefore updated it in NIFs only.

**Comment by michaelklishin** [comment]
Resolved in #9.
